### PR TITLE
Added an IWETH10 interface

### LINKED ISSUE #60: add & implement an IWETH10 interface
This file would be useful for anyone who wishes to integrate with WETH10

### PR DESCRIPTION
**Pull request by lepidotteri**
Fixes #60

### CODE REVIEW

**Review by albertocuestacanada — CHANGES_REQUESTED** [review]
Thanks for this!

The interface should also contain methods for the public variables, such as:

`function balanceOf(address) external view returns(uint256)`

**Comment by lepidotteri** [comment]
> Thanks for this!
> 
> The interface should also contain methods for the public variables, such as:
> 
> `function balanceOf(address) external view returns(uint256)`

I added them explicitly, but as you know solc generates these getters itself for public vars

**Comment by albertocuestacanada** [comment]
Interfaces have nothing to do with the methods created by the compiler. Interfaces have two purposes:
1. When used by other contract, they specify the methods and variables that are exposed. Without a `balanceOf` method in the `IWETH10` interface any other contract using `IWETH10` couldn't check balances.
2. For the contract implementing the interface, it makes the compiler check that the interface methods are implemented, either as explicit functions or as state variables (for `view` methods). Without `balanceOf` in the interface `IWETH10.sol` wouldn't be compliant with the ERC20 standard, coded in the IERC20 interface.

**Comment by albertocuestacanada** [comment]
1. Corrected the renaming of `nonces` to `nonceOf`. Even if I like `nonceOf` better, in IERC2612 it is `nonces`.
2. Introduced the `yarn.lock` file. Some recent package breaks `eth-permit`.
3. Brought IERC20 and IERC2612 into the repo, and made IWETH10 inherit them.
4. Restored the `totalSupply()` method. Removing it in the first place might have been my fault.

**Pull request merged**
