### PR TITLE
Introduce modifier validateRecipient() to deduplicate code

### PR DESCRIPTION
**Pull request by k06a**

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
Thanks for this, could you please paste the gas costs before and after this change?

I remember trying this a while ago, but it raised the gas costs (I think it copies the parameters to memory). That's why there is so much duplicated code everywhere.

**Comment by k06a** [comment]
Let's just add this to the project first: https://github.com/cgewecke/eth-gas-reporter

**Comment by albertocuestacanada** [comment]
It's there, if you run the tests you'll get the gas report.

https://github.com/WETH10/WETH10/blob/a6cfec345baff1361d2f2484761d6bea1e3e9c89/package.json#L31

**Comment by k06a** [comment]
@albertocuestacanada cool!

**Comment by albertocuestacanada** [comment]
Gas costs before:
```
·--------------------------------------------|---------------------------|---------------|----------------------------·
|            Solc version: 0.7.0             ·  Optimizer enabled: true  ·  Runs: 20000  ·  Block limit: 9500000 gas  │
·············································|···························|···············|·····························
|  Methods                                                                                                            │
····················|························|·············|·············|···············|··············|··············
|  Contract         ·  Method                ·  Min        ·  Max        ·  Avg          ·  # calls     ·  eur (avg)  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMint             ·          -  ·          -  ·       101472  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndReenter   ·          -  ·          -  ·       120137  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndWithdraw  ·          -  ·          -  ·       125289  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  approve               ·      43894  ·      44266  ·        43987  ·           8  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  deposit               ·          -  ·          -  ·        44778  ·          25  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositTo             ·          -  ·          -  ·        45279  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositToAndCall      ·          -  ·          -  ·        50555  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  permit                ·          -  ·          -  ·        71777  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transfer              ·          -  ·          -  ·        51432  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferAndCall       ·          -  ·          -  ·        56683  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferFrom          ·      44886  ·      52868  ·        49883  ·           3  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdraw              ·          -  ·          -  ·        37560  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawFrom          ·      31438  ·      39432  ·        35435  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawTo            ·          -  ·          -  ·        38007  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  approve               ·          -  ·          -  ·        43871  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  deposit               ·          -  ·          -  ·        43566  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth10ToWeth9         ·          -  ·          -  ·        57621  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth9ToWeth10         ·          -  ·          -  ·        58313  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  Deployments                               ·                                           ·  % of limit  ·             │
·············································|·············|·············|···············|··············|··············
|  TestERC677Receiver                        ·          -  ·          -  ·       169429  ·       1.8 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  TestFlashMinter                           ·          -  ·          -  ·       543869  ·       5.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH10                                    ·          -  ·          -  ·      1968052  ·      20.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH9                                     ·          -  ·          -  ·       565921  ·         6 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WethConverter                             ·          -  ·          -  ·       297489  ·       3.1 %  ·          -  │
·--------------------------------------------|-------------|-------------|---------------|--------------|-------------·
```

**Comment by albertocuestacanada** [comment]
Gas costs after:
```
·--------------------------------------------|---------------------------|---------------|----------------------------·
|            Solc version: 0.7.0             ·  Optimizer enabled: true  ·  Runs: 20000  ·  Block limit: 9500000 gas  │
·············································|···························|···············|·····························
|  Methods                                                                                                            │
····················|························|·············|·············|···············|··············|··············
|  Contract         ·  Method                ·  Min        ·  Max        ·  Avg          ·  # calls     ·  eur (avg)  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMint             ·          -  ·          -  ·       101472  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndReenter   ·          -  ·          -  ·       120137  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndWithdraw  ·          -  ·          -  ·       125289  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  approve               ·      43894  ·      44266  ·        43987  ·           8  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  deposit               ·          -  ·          -  ·        44778  ·          25  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositTo             ·          -  ·          -  ·        45346  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositToAndCall      ·          -  ·          -  ·        50624  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  permit                ·          -  ·          -  ·        71777  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transfer              ·          -  ·          -  ·        51504  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferAndCall       ·          -  ·          -  ·        56683  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferFrom          ·      44958  ·      52940  ·        49955  ·           3  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdraw              ·          -  ·          -  ·        37560  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawFrom          ·      31505  ·      39499  ·        35502  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawTo            ·          -  ·          -  ·        38074  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  approve               ·          -  ·          -  ·        43871  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  deposit               ·          -  ·          -  ·        43566  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth10ToWeth9         ·          -  ·          -  ·        57688  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth9ToWeth10         ·          -  ·          -  ·        58380  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  Deployments                               ·                                           ·  % of limit  ·             │
·············································|·············|·············|···············|··············|··············
|  TestERC677Receiver                        ·          -  ·          -  ·       169429  ·       1.8 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  TestFlashMinter                           ·          -  ·          -  ·       543869  ·       5.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH10                                    ·          -  ·          -  ·      2262056  ·      23.8 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH9                                     ·          -  ·          -  ·       565921  ·         6 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WethConverter                             ·          -  ·          -  ·       297489  ·       3.1 %  ·          -  │
·--------------------------------------------|-------------|-------------|---------------|--------------|-------------·
```

**Comment by albertocuestacanada** [comment]
Unfortunately, modifiers use gas, so we must keep the code duplication.

**Pull request closed without merging**
