### PR TITLE
Add WETH10Deployer.sol with CREATE2

### PR DESCRIPTION
**Pull request by Ro5s**
add WETH10 factory with CREATE2 / single deploy factory

### CODE REVIEW

**Comment by Ro5s** [comment]
noticed a funky issue here. Though currently this deployer contract can compute and deploy to a predictable address, this does not work across chains. This is expected, I guess, as I use `address(this)` which will necessarily be different across/chain deployer contracts:

`abi.encodePacked(bytes1(0xff), address(this), salt, bytecodeHash)` in `computeAddress()`

However, if I switch value to `msg.sender` which is consistent across/chain value here, I *can call `computerAddress()` and retrieve same address across/chain. HOWEVER, the `deployWETH10` function ends up creating inconsistent addresses than what is computed.... :confused: 

Any idea what I might be screwing up here @abcoathup :cat: ?

**Comment by abcoathup** [comment]
> Any idea what I might be screwing up here @abcoathup 🐱 ?

The calculating of the address and the actual deployment are different code when they need to be the same.
You want to remove any thing that will be different across chains, so remove `address(this)`.

**Comment by abcoathup** [comment]
Alternatively, could use Nick's method to deploy (as done in EIP 1820)

https://eips.ethereum.org/EIPS/eip-1820

**Comment by wighawag** [comment]
let's reuse existing solution  : https://github.com/Arachnid/deterministic-deployment-proxy
- It is live on mainnet :  https://etherscan.io/address/0x4e59b44847b379578588920ca78fbf26c0b4956c
- it combines nick's method with a minimal create2 based deployer to ensure same address across network
- it is included in https://github.com/wighawag/hardhat-deploy but can be easily invoked by making a raw tx

**Comment by wighawag** [comment]
with ethers :

```
const unsignedTx = factory.getDeployTransaction(...args, overrides);
unsignedTx.to = "0x4e59b44847b379578588920cA78FbF26c0B4956C";
unsignedTx.data = "0x0000000000000000000000000000000000000000000000000000000000000000" + unsignedTx.data.slice(2);
```

**Comment by moodysalem** [comment]
the best way to do this for a single contract is just https://github.com/WETH10/WETH10/issues/14#issuecomment-708917121

no downsides afaik

**Comment by wighawag** [comment]
@moodysalem 
The downside is that it require trust in the owner of the EOA to not make tx before hand
The method I described above is better in my opinion, and is quite simple.

**Comment by moodysalem** [comment]
> @moodysalem 
> 
> The downside is that it require trust in the owner of the EOA to not make tx before hand
> 
> The method I described above is better in my opinion, and is quite simple.

idk if trust is the right word considering if the eoa holder messes up they can just start over with a new address

**Comment by wighawag** [comment]
The issue is for new network or network not considered by the private key
owner.
Once the weth is used it becomes an issue.

**Comment by moodysalem** [comment]
> The issue is for new network or network not considered by the private key owner. Once the weth is used it becomes an issue.

sorry, just asking for my understanding, what about networks where the create2 deployer isn't deployed? how does this get around that issue?

and anyway, with immutable in solidity, it's not as big a deal for weth to not be at the same address everywhere including unknown/private testnets (since constants/immutable have same/similar gas costs for accessing)

**Comment by wighawag** [comment]
@moodysalem as mentioned in my [comment](https://github.com/WETH10/WETH10/pull/22#issuecomment-715420941) it uses Nick technic, so it can itself be deterministically deployed on every network that accept 100 Gwei gas price

Note that having the same address, is also very important for other contracts that want to have the same address on every network. if they have to hardcode different address on different network, it become more complicated

**Comment by wighawag** [comment]
I created a PR for deterministic deployment that use buidler-deploy : https://github.com/WETH10/WETH10/pull/72

buidler-deploy use the exact technic mentioned above.

As mentioned in the PR, to benefit from create2 determinism issue https://github.com/WETH10/WETH10/issues/69 need to be solved first

**Comment by albertocuestacanada** [comment]
Obsolete via #72

**Pull request closed without merging**
