### PR TITLE
Deterministic deployment using buidler deploy

### PR DESCRIPTION
**Pull request by wighawag**
The PR add deterministic deployment by using buidler-deploy

The only thing blocking from having same address across network is https://github.com/WETH10/WETH10/issues/69 as the constructor argument will generate a different create2 address

### CODE REVIEW

**Comment by wighawag** [comment]
Oh and because of #69 I currently set the deployment to use "0x000000000000000000000000000000000000" for WETH9 address
this is obviously not what we want. This is just to demonstrate the deterministic deployment

**Review by albertocuestacanada — APPROVED** [review]
Awesome work, thank you!

WETH10 doesn't take a parameter anymore, having taken the conversion functions to `WethConverter.sol`.

One question, how do you set it up to save metadata, so that we can user `etherscan-verify`? I get this: ```Contract WETH10 was deployed without saving metadata. Cannot submit to etherscan, skipping.```

**Comment by wighawag** [comment]
re the metadata error, this is weird, it was tested before, maybe it was a cache issue as hardhat use timestamp for cache breaking

try deleting the cache and redeploying. Delete also the deployments folder: it will not actually redeploy as it use deterministic address, but it will be able to reconstruct the metadata

yes it uses create2 + nick method for the create2 deployer

**Comment by wighawag** [comment]
I merge the changes from main.
WethConverter is also deterministically deployed

**Comment by albertocuestacanada** [comment]
Still not getting etherscan-verify to work, but the deploy part works fine, so let's merge.

```
verifying WETH10 (0xb2253A312551b3b4F92c64df59f5A3023Df702B8) ...
contract WETH10 failed to submit : "NOTOK" [object Object]
```

**Comment by wighawag** [comment]
@albertocuestacanada 
Did you delete the respective deployments folder ?
I see the WETH10 address you have is not the latest one which should be : 0x02d2F830914ac2C368fd9D655f7F3C7A13E45e77

try that for kovan for example (I did not verify that one yet):
```
rm -Rf cache
rm -Rf deployments/kovan
yarn kovan:deploy
yarn buidler --network kovan etherscan-verify --api-key <apiKey> --license GPL-3.0 --force-license
```

**Pull request merged**
