### PR TITLE
fix: reduced gas costs

### PR DESCRIPTION
**Pull request by albertocuestacanada**
Removed duplicate SLOADs for `balanceOf[msg.sender]`

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
Before:
```
·--------------------------------------------|---------------------------|---------------|----------------------------·
|            Solc version: 0.7.0             ·  Optimizer enabled: true  ·  Runs: 20000  ·  Block limit: 9500000 gas  │
·············································|···························|···············|·····························
|  Methods                                                                                                            │
····················|························|·············|·············|···············|··············|··············
|  Contract         ·  Method                ·  Min        ·  Max        ·  Avg          ·  # calls     ·  eur (avg)  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMint             ·          -  ·          -  ·       101472  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndReenter   ·          -  ·          -  ·       120137  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndWithdraw  ·          -  ·          -  ·       125289  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  approve               ·      43894  ·      44266  ·        43987  ·           8  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  deposit               ·          -  ·          -  ·        44778  ·          25  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositTo             ·          -  ·          -  ·        45279  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositToAndCall      ·          -  ·          -  ·        50555  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  permit                ·          -  ·          -  ·        71777  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transfer              ·          -  ·          -  ·        51432  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferAndCall       ·          -  ·          -  ·        56683  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferFrom          ·      44886  ·      52868  ·        49883  ·           3  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdraw              ·          -  ·          -  ·        37560  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawFrom          ·      31438  ·      39432  ·        35435  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawTo            ·          -  ·          -  ·        38007  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  approve               ·          -  ·          -  ·        43871  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  deposit               ·          -  ·          -  ·        43566  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth10ToWeth9         ·          -  ·          -  ·        57621  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth9ToWeth10         ·          -  ·          -  ·        58313  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  Deployments                               ·                                           ·  % of limit  ·             │
·············································|·············|·············|···············|··············|··············
|  TestERC677Receiver                        ·          -  ·          -  ·       169429  ·       1.8 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  TestFlashMinter                           ·          -  ·          -  ·       543869  ·       5.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH10                                    ·          -  ·          -  ·      1968052  ·      20.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH9                                     ·          -  ·          -  ·       565921  ·         6 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WethConverter                             ·          -  ·          -  ·       297489  ·       3.1 %  ·          -  │
·--------------------------------------------|-------------|-------------|---------------|--------------|-------------·
```

**Comment by albertocuestacanada** [comment]
After:
```
·--------------------------------------------|---------------------------|---------------|----------------------------·
|            Solc version: 0.7.0             ·  Optimizer enabled: true  ·  Runs: 20000  ·  Block limit: 9500000 gas  │
·············································|···························|···············|·····························
|  Methods                                                                                                            │
····················|························|·············|·············|···············|··············|··············
|  Contract         ·  Method                ·  Min        ·  Max        ·  Avg          ·  # calls     ·  eur (avg)  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMint             ·          -  ·          -  ·       100668  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndReenter   ·          -  ·          -  ·       118529  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  TestFlashMinter  ·  flashMintAndWithdraw  ·          -  ·          -  ·       123687  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  approve               ·      43894  ·      44266  ·        43987  ·           8  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  deposit               ·          -  ·          -  ·        44778  ·          25  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositTo             ·          -  ·          -  ·        45279  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  depositToAndCall      ·          -  ·          -  ·        50555  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  permit                ·          -  ·          -  ·        71777  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transfer              ·          -  ·          -  ·        50634  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferAndCall       ·          -  ·          -  ·        55885  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  transferFrom          ·      44886  ·      52868  ·        49883  ·           3  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdraw              ·          -  ·          -  ·        36762  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawFrom          ·      31438  ·      39432  ·        35435  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdrawTo            ·          -  ·          -  ·        37209  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  approve               ·          -  ·          -  ·        43871  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WETH9            ·  deposit               ·          -  ·          -  ·        43566  ·           2  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth10ToWeth9         ·          -  ·          -  ·        57621  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  WethConverter    ·  weth9ToWeth10         ·          -  ·          -  ·        58313  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
|  Deployments                               ·                                           ·  % of limit  ·             │
·············································|·············|·············|···············|··············|··············
|  TestERC677Receiver                        ·          -  ·          -  ·       169429  ·       1.8 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  TestFlashMinter                           ·          -  ·          -  ·       543869  ·       5.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH10                                    ·          -  ·          -  ·      1967176  ·      20.7 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WETH9                                     ·          -  ·          -  ·       565921  ·         6 %  ·          -  │
·············································|·············|·············|···············|··············|··············
|  WethConverter                             ·          -  ·          -  ·       297489  ·       3.1 %  ·          -  │
·--------------------------------------------|-------------|-------------|---------------|--------------|-------------·
```

**Comment by k06a** [comment]
Wish to know how to setup this thing: https://github.com/Synthetixio/synthetix/pull/670/checks?check_run_id=1005666516

**Comment by k06a** [comment]
WDYT about using this method? https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/math/SafeMath.sol#L60

**Comment by albertocuestacanada** [comment]
This project definitely needs some CI, we don't even run automated tests which is embarrasing.

We are using only external functions to save on gas costs.

**Comment by jacob-eliosoff** [comment]
@albertocuestacanada this is great.  Can you not do the same trick in `withdrawFrom()` too?  Or is there risk of the balance being changed by the `emit Approval` or something.

**Comment by albertocuestacanada** [comment]
I missed `withdrawFrom`! That's why you DRY. Thanks @jacob-eliosoff.

**Comment by k06a** [comment]
@albertocuestacanada I mean using this method would allow having 1 row instead of 3 and keep all the benefits:
```solidity
uint256 balance = balanceOf[msg.sender];
require(amount >= balance, "Not enough balance");
balanceOf[msg.sender] = balance - amount;
```
=>
```solidity
balanceOf[msg.sender] = balanceOf[msg.sender].sub(amount, "Not enough balance");
```

**Comment by jacob-eliosoff** [comment]
I like @k06a's approach!  As long as it doesn't add more than like 10 gas

**Comment by albertocuestacanada** [comment]
I like clean code as well, but unfortunately it adds 119 gas.

Without SafeMath:
```
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdraw              ·          -  ·          -  ·        36762  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
```

With SafeMath:
```
····················|························|·············|·············|···············|··············|··············
|  WETH10           ·  withdraw              ·          -  ·          -  ·        36871  ·           1  ·          -  │
····················|························|·············|·············|···············|··············|··············
```

**Pull request merged**
